[project]
name = "pypik"
version = "0.1.0"
description = "Convert pik format files into PowerPoint objects, SVG, and other formats via an intermediate tree structure"
readme = "README.md"
authors = [
    { name = "Miki Yutani", email = "mkyutani@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pypik = "pypik:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
